openapi: 3.0.1
info:
  title: 测试sw API
  description: >
    Open for cc RESTful API docs.
    Version 0.0.1: All interfaces
  license:
    name: MIT License
  version: 0.0.1
tags:
  - name: test
    description: 测试接口
paths:
  /test:
    get:
      tags:
        - test
      summary: test 测试接口
      description: test for RESTful API
      # parameters:
      #   - $ref: "#/components/parameters/name"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: '请求名称'
              required:
                true
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    description: 响应code
                  message:
                    type: string
                    description: 响应提示语
                required:
                  - code
                  - message
              example:
                code: 200
                message: '请求成功'
